import React from 'react'
import Link from 'next/link'
import Head from 'next/head'


const Nosotros = () => {
  return (
    <div>
        <Head>
            <title>Guitar App - Nosotros</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
      </Head>
        <h1 className="heading">Desde Nosotros</h1>

        <Link href="/ ">Ir a Inicio</Link>
    </div>
  )
}

export default Nosotros